errors = {
    "COMMAND_NOT_ALLOWED": "No tienes permitido usar este comando.",
    "BADWORDS_NOT_ENABLED": "La moderación de palabras no está activada para la sala {}.",
    "NO_BADWORDS": "No hay palabras en lista negra para la sala {}.",
    "BADWORDS_ENABLED": "La moderación de palabras ya está activada para la sala {}.",
    "BADWORDS_DISABLED": "La moderación de palabras ya está desactivada para la sala {}.",
    "BADWORD_EXISTS": "Esa palabra ya está en la lista negra de la sala {}.",
    "BADWORD_NOT_EXISTS": "Esa palabra no se encuentra en la lista negra de la sala {}.",
    "WORD_NOT_SPECIFIED": "No se especificó palabra.",
    "BADNICKS_NOT_ENABLED": "La moderación de nicks no está actiada para la sala {}.",
    "NO_BADNICKS": "No hay nicks en lista negra para la sala {}.",
    "BADNICKS_ENABLED": "La moderación de nicks ya está activada para la sala {}.",
    "BADNICKS_DISABLED": "La moderación de nicks ya está desactivada para la sala {}.",
    "BADNICK_EXISTS": "Ese nick ya está en la lista negra de la sala {}.",
    "BADNICK_NOT_EXISTS": "Ese nick no se encuentra en la lista negra de la sala {}.",
    "NICK_NOT_SPECIFIED": "No se especificó nick.",
    "RULES_NOT_ENABLED": "Las gestion de reglamento no está activada para la sala {}.",
    "NO_RULES": "No hay ninguna regla en el reglamento de la sala {}.",
    "RULES_ENABLED": "La gestión de reglamento ya está activada para la sala {}.",
    "RULES_DISABLED": "La gestión de reglamento ya está desactivada para la sala {}.",
    "RULE_EXISTS": "Ya hay una regla con el número {} en el reglamento de la sala {}.",
    "RULE_NOT_EXISTS": "No existe la regla número {} en el reglamento de la sala {}.",
    "RULE_NOT_SPECIFIED": "No se especificó regla.",
    "RULE_NUM_NOT_SPECIFIED": "No se especificó número de regla.",
    "RULE_DESC_NOT_SPECIFIED": "No se especificó descripción de regla.",
    "INVALID_NUM": "{} no es un número válido.",
    "UNKNOWN_COMMAND": "Comando {} desconocido.",
    "DB_ERROR": "Database error: {}.",
    "DB_CONNECTION_ERROR": "Error connecting to MariaDB engine: {}.",
}
