errors = {
    "COMMAND_NOT_ALLOWED": "No tienes permitido usar este comando.",
    "BADWORDS_NOT_ENABLED": "La moderación de palabras no está activada para la sala {}.",
    "NO_BADWORDS": "No hay palabras en lista negra para la sala {}.",
    "BADWORDS_ENABLED": "La moderación de palabras ya está activada para la sala {}.",
    "BADWORDS_DISABLED": "La moderación de palabras ya está desactivada para la sala {}.",
    "BADWORD_EXISTS": "Esa palabra ya está en la lista negra de la sala {}.",
    "BADWORD_NOT_EXISTS": "Esa palabra no se encuentra en la lista negra de la sala {}.",
    "WORD_NOT_SPECIFIED": "No se especificó palabra.",
    "BADNICKS_NOT_ENABLED": "La moderación de nicks no está actiada para la sala {}.",
    "NO_BADNICKS": "No hay nicks en lista negra para la sala {}.",
    "BADNICKS_ENABLED": "La moderación de nicks ya está activada para la sala {}.",
    "BADNICKS_DISABLED": "La moderación de nicks ya está desactivada para la sala {}.",
    "BADNICK_EXISTS": "Ese nick ya está en la lista negra de la sala {}.",
    "BADNICK_NOT_EXISTS": "Ese nick no se encuentra en la lista negra de la sala {}.",
    "NICK_NOT_SPECIFIED": "No se especificó nick.",
    "RULES_NOT_ENABLED": "Las gestion de reglamento no está activada para la sala {}.",
    "NO_RULES": "No hay ninguna regla en el reglamento de la sala {}.",
    "RULES_ENABLED": "La gestión de reglamento ya está activada para la sala {}.",
    "RULES_DISABLED": "La gestión de reglamento ya está desactivada para la sala {}.",
    "RULE_EXISTS": "Ya hay una regla con el número {} en el reglamento de la sala {}.",
    "RULE_NOT_EXISTS": "No existe la regla número {} en el reglamento de la sala {}.",
    "RULE_NOT_SPECIFIED": "No se especificó regla.",
    "RULE_NUM_NOT_SPECIFIED": "No se especificó número de regla.",
    "RULE_DESC_NOT_SPECIFIED": "No se especificó descripción de regla.",
    "INVALID_NUM": "{} no es un número válido.",
    "UNKNOWN_COMMAND": "Comando {} desconocido.",
    "DB_ERROR": "Database error: {}.",
    "DB_CONNECTION_ERROR": "Error connecting to MariaDB engine: {}.",
}

queries = {
    "GET_ALL_CHANNELS": "SELECT * FROM channel;",
    "GET_BADWORDS": "SELECT badword.badword, channel.channel_name FROM badword JOIN channel ON badword.channel_id = channel.channel_id;",
    "GET_BADNICKS": "SELECT badnick.badnick, channel.channel_name FROM badnick JOIN channel ON badnick.channel_id = channel.channel_id;",
    "GET_RULES": "SELECT rule.rule_number, rule.rule_desc, channel.channel_name FROM rule JOIN channel ON rule.channel_id = channel.channel_id ORDER BY rule.rule_number ASC;",
    "JOIN_CHANNEL": "INSERT INTO channel(channel_name) VALUE(?);",
    "TOGGLE_BADWORDS": "UPDATE channel SET channel.badwords_enabled = ? WHERE channel.channel_name = ?;",
    "ADD_BADWORD": "INSERT INTO badword VALUES(?, (SELECT channel_id FROM channel WHERE channel_name = ?));",
    "DELETE_BADWORD": "DELETE badword FROM badword JOIN channel ON badword.channel_id = channel.channel_id WHERE badword.badword = ? AND channel.channel_name = ?;",
    "TOGGLE_BADNICKS": "UPDATE channel SET channel.badnicks_enabled = ? WHERE channel.channel_name = ?;",
    "ADD_BADNICK": "INSERT INTO badnick VALUES(?, (SELECT channel_id FROM channel WHERE (LOWER(channel.channel_name) = ?)));",
    "DELETE_BADNICK": "DELETE badnick FROM badnick JOIN channel ON badnick.channel_id = channel.channel_id WHERE badnick.badnickk = ? AND channel.channel_name = ?;",
    "TOGGLE_RULES": "UPDATE channel SET channel.rules_enabled = ? WHERE channel.channel_name = ?;",
    "ADD_RULE": "INSERT INTO rule VALUES(?, (SELECT channel.channel_id FROM channel WHERE channel.channel_name = ?), ?);",
    "UPDATE_RULE": "UPDATE rule JOIN channel ON rule.channel_id = channel.channel_id SET rule.rule_desc = ? WHERE channel.channel_name = ? AND rule.rule_number = ?;",
    "DELETE_RULE": "DELETE rule FROM rule JOIN channel ON rule.channel_id = channel.channel_id WHERE rule.rule_number = ? AND channel.channel_name = ?;",
}
